### ISSUE TITLE
Is necessary enable bundle in kernel?

### ISSUE THREAD

**Issue by dEROZA** [symfony-bundles/json-request-bundle#12]
Is is necessary with Symfony 4.4? Because I found that in bundles.php already enabled by default after installation. In my newbie projects' no kernel class..

```

In a default Symfony application that uses Symfony Flex, bundles are enabled/disabled automatically for you when installing/removing them, so you don't need to look at or edit this bundles.php file.

```

P.S. please, update readme.. thx.

**Comment by khaperets** [comment]
Hi!
README updated, thanks
